# Laboratory exercise 6

The notebook contains exercises connected to auditory exercise 7. For any questions feel free to contact assistant: eda.jovicic@fer.hr

The main task of this notebook is to make predictions using supported learning with the Scikit Learn library. The goal is to predict the grade in Math considering other features of the student.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

1. Load the cleaned dataset from the first exercise. If you haven't saved the dataset, rerun the exercise and save the final dataset.

In [3]:
#solution
df = pd.read_csv('students_cleaned.csv') 
df


Unnamed: 0  Gender  EthnicGroup  ParentEduc     LunchType  TestPrep  \
0               0  female            2           1      standard         1   
1               1  female            2           5      standard         1   
2               2  female            1           3      standard         1   
3               3    male            0           0  free/reduced         1   
4               4    male            2           5      standard         1   
...           ...     ...          ...         ...           ...       ...   
29112       29112  female            3           2      standard         1   
29113       29113    male            4           2      standard         1   
29114       29114  female            2           2  free/reduced         0   
29115       29115  female            3           0      standard         0   
29116       29116    male            1           5      standard         1   

       ParentMaritalStatus  PracticeSport  IsFirstChild  NrSiblings  \
0                        1              1             1         3.0   
1                        1              2             1         0.0   
2                        2              2             1         4.0   
3                        1              0             0         1.0   
4                        1              2             1         0.0   
...                    ...            ...           ...         ...   
29112                    2              2             0         2.0   
29113                    2              1             0         1.0   
29114                    1              2             0         1.0   
29115                    1              1             0         3.0   
29116                    1              0             0         1.0   

       TransportMeans  WklyStudyHours  MathScore  ReadingScore  WritingScore  \
0                   1               1         71            71            74   
1                   2               0         69            90            88   
2                   1               1         87            93            91   
3                   2               0         45            56            42   
4                   1               0         76            78            75   
...               ...             ...        ...           ...           ...   
29112               1               0         59            61            65   
29113               0               0         58            53            51   
29114               0               0         61            70            67   
29115               1               0         82            90            93   
29116               1               0         64            60            58   

       Gender_female  Gender_male  LunchType_free/reduced  LunchType_standard  
0                1.0          0.0                     0.0                 1.0  
1                1.0          0.0                     0.0                 1.0  
2                1.0          0.0                     0.0                 1.0  
3                0.0          1.0                     1.0                 0.0  
4                0.0          1.0                     0.0                 1.0  
...              ...          ...                     ...                 ...  
29112            1.0          0.0                     0.0                 1.0  
29113            0.0          1.0                     0.0                 1.0  
29114            1.0          0.0                     1.0                 0.0  
29115            1.0          0.0                     0.0                 1.0  
29116            0.0          1.0                     0.0                 1.0  

[29117 rows x 19 columns]

2. Transform the MathScore feature into grades (1-5) using the following scoring system:

|   MathScore |  Grade  |
| ----------- | ------- |
|  88 - 100   |    5    |
|  75 - 87    |    4    |
|  63 - 74    |    3    |
|  50 - 62    |    2    |
|   0 - 49    |    1    |

In [27]:
#solution
score_bins = [-1, 49, 62, 74, 87, 100]
grade_labels = [1, 2, 3, 4, 5]

# Create a new column 'Grade' based on the scoring system
df['Grade'] = pd.cut(df['MathScore'], bins=score_bins, labels=grade_labels, include_lowest=True)

# Display the updated DataFrame
print(df[['MathScore', 'Grade']])
# Display the DataFrame with the new 'Grade' column
df



       MathScore Grade
0             71     3
1             69     3
2             87     4
3             45     1
4             76     4
...          ...   ...
29112         59     2
29113         58     2
29114         61     2
29115         82     4
29116         64     3

[29117 rows x 2 columns]


Unnamed: 0  Gender  EthnicGroup  ParentEduc  LunchType  TestPrep  \
0               0  female            2           1          0         1   
1               1  female            2           5          0         1   
2               2  female            1           3          0         1   
3               3    male            0           0          1         1   
4               4    male            2           5          0         1   
...           ...     ...          ...         ...        ...       ...   
29112       29112  female            3           2          0         1   
29113       29113    male            4           2          0         1   
29114       29114  female            2           2          1         0   
29115       29115  female            3           0          0         0   
29116       29116    male            1           5          0         1   

       ParentMaritalStatus  PracticeSport  IsFirstChild  NrSiblings  ...  \
0                        1              1             1         3.0  ...   
1                        1              2             1         0.0  ...   
2                        2              2             1         4.0  ...   
3                        1              0             0         1.0  ...   
4                        1              2             1         0.0  ...   
...                    ...            ...           ...         ...  ...   
29112                    2              2             0         2.0  ...   
29113                    2              1             0         1.0  ...   
29114                    1              2             0         1.0  ...   
29115                    1              1             0         3.0  ...   
29116                    1              0             0         1.0  ...   

       WklyStudyHours  MathScore  ReadingScore  WritingScore  Gender_female  \
0                   1         71            71            74            1.0   
1                   0         69            90            88            1.0   
2                   1         87            93            91            1.0   
3                   0         45            56            42            0.0   
4                   0         76            78            75            0.0   
...               ...        ...           ...           ...            ...   
29112               0         59            61            65            1.0   
29113               0         58            53            51            0.0   
29114               0         61            70            67            1.0   
29115               0         82            90            93            1.0   
29116               0         64            60            58            0.0   

       Gender_male  LunchType_free/reduced  LunchType_standard  Grade  \
0              0.0                     0.0                 1.0      3   
1              0.0                     0.0                 1.0      3   
2              0.0                     0.0                 1.0      4   
3              1.0                     1.0                 0.0      1   
4              1.0                     0.0                 1.0      4   
...            ...                     ...                 ...    ...   
29112          0.0                     0.0                 1.0      2   
29113          1.0                     0.0                 1.0      2   
29114          0.0                     1.0                 0.0      2   
29115          0.0                     0.0                 1.0      4   
29116          1.0                     0.0                 1.0      3   

      gender_numeric  
0                  1  
1                  1  
2                  1  
3                  0  
4                  0  
...              ...  
29112              1  
29113              0  
29114              1  
29115              1  
29116              0  

[29117 rows x 21 columns]

3. Divide the dataset into features (X) and predictions (y). For features we will use all the columns except MathScore, ReadingScore and WritingScore. For predictions we will use the MathScore column. Split the dataset into training and testing sets. The split should be done in a  70-30% ratio.

In [28]:
#X (all features except MathScore, ReadingScore, WritingScore) and y (MathScore)
df['LunchType'].replace({'standard': 0, 'free/reduced':1}, inplace=True)
df['gender_numeric'] = df['Gender'].replace({'male': 0, 'female': 1})
feature_cols = ['gender_numeric', 'EthnicGroup', 'ParentEduc', 'LunchType', 'TestPrep', 'ParentMaritalStatus', 'PracticeSport', 'IsFirstChild', 'NrSiblings', 'TransportMeans','WklyStudyHours',]
X = df[feature_cols]
y = df.Grade

X.describe()


gender_numeric   EthnicGroup    ParentEduc     LunchType      TestPrep  \
count    29117.000000  29117.000000  29117.000000  29117.000000  29117.000000   
mean         0.503864      2.172957      3.080881      0.350173      0.675276   
std          0.499994      1.105460      2.190324      0.477032      0.468280   
min          0.000000      0.000000      0.000000      0.000000      0.000000   
25%          0.000000      1.000000      1.000000      0.000000      0.000000   
50%          1.000000      2.000000      3.000000      0.000000      1.000000   
75%          1.000000      3.000000      5.000000      1.000000      1.000000   
max          1.000000      4.000000      6.000000      1.000000      1.000000   

       ParentMaritalStatus  PracticeSport  IsFirstChild    NrSiblings  \
count         29117.000000   29117.000000  29117.000000  29117.000000   
mean              1.109077       1.372635      0.642030      2.147714   
std               0.676667       0.709069      0.479411      1.428635   
min               0.000000       0.000000      0.000000      0.000000   
25%               1.000000       1.000000      0.000000      1.000000   
50%               1.000000       2.000000      1.000000      2.000000   
75%               2.000000       2.000000      1.000000      3.000000   
max               3.000000       2.000000      1.000000     26.000000   

       TransportMeans  WklyStudyHours  
count    29117.000000    29117.000000  
mean         0.730501        0.607995  
std          0.633428        0.760503  
min          0.000000        0.000000  
25%          0.000000        0.000000  
50%          1.000000        0.000000  
75%          1.000000        1.000000  
max          2.000000        2.000000

In [29]:
#splitting the dataset into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

4. Create a Random Forest model, with max_depth=5 and n_estimators=20. Train the model using training set, and then test it on testing set. Display the confusion matrix. Show precision, recall and F1 score for all grades. 

In [36]:
#Random Forest model

df.isna().sum()
rf_model = RandomForestClassifier(max_depth=5, n_estimators=20, random_state=42)
rf_model.fit(X,y)



# Predict on the testing set
y_pred = rf_model.predict(X_test)

# Display confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

# Display precision, recall, and F1 score for all grades
class_report = classification_report(y_test, y_pred)
print("\nClassification Report:")
print(class_report)




[[  71  704  370   29    0]
 [  37  912 1127  124    0]
 [  13  613 1585  336    0]
 [   1  280 1229  516    1]
 [   0   28  406  348    6]]

Classification Report:
              precision    recall  f1-score   support

           1       0.58      0.06      0.11      1174
           2       0.36      0.41      0.39      2200
           3       0.34      0.62      0.44      2547
           4       0.38      0.25      0.31      2027
           5       0.86      0.01      0.02       788

    accuracy                           0.35      8736
   macro avg       0.50      0.27      0.25      8736
weighted avg       0.43      0.35      0.31      8736



5. The accuracy of our model is not the best. The reason could be having too many possible classes (grades). Let's transform the data again, but this time, instead of predicting grades, we want to predict whether the student will pass (grades 2, 3, 4 and 5) or fail (grade 1) math. After transforming the MathScore accordingly (0 - failed, 1 - passed), repeat task 4 and compare the results.

In [54]:
#transform grades into failed (0) or passed (1)
#solution
df['Grade'] = pd.cut(df['MathScore'], bins=[0, 49, 101], labels=[0, 1], right=True, include_lowest=True)
df
df.isna().sum()
df


Unnamed: 0  Gender  EthnicGroup  ParentEduc  LunchType  TestPrep  \
0               0  female            2           1          0         1   
1               1  female            2           5          0         1   
2               2  female            1           3          0         1   
3               3    male            0           0          1         1   
4               4    male            2           5          0         1   
...           ...     ...          ...         ...        ...       ...   
29112       29112  female            3           2          0         1   
29113       29113    male            4           2          0         1   
29114       29114  female            2           2          1         0   
29115       29115  female            3           0          0         0   
29116       29116    male            1           5          0         1   

       ParentMaritalStatus  PracticeSport  IsFirstChild  NrSiblings  ...  \
0                        1              1             1         3.0  ...   
1                        1              2             1         0.0  ...   
2                        2              2             1         4.0  ...   
3                        1              0             0         1.0  ...   
4                        1              2             1         0.0  ...   
...                    ...            ...           ...         ...  ...   
29112                    2              2             0         2.0  ...   
29113                    2              1             0         1.0  ...   
29114                    1              2             0         1.0  ...   
29115                    1              1             0         3.0  ...   
29116                    1              0             0         1.0  ...   

       WklyStudyHours  MathScore  ReadingScore  WritingScore  Gender_female  \
0                   1         71            71            74            1.0   
1                   0         69            90            88            1.0   
2                   1         87            93            91            1.0   
3                   0         45            56            42            0.0   
4                   0         76            78            75            0.0   
...               ...        ...           ...           ...            ...   
29112               0         59            61            65            1.0   
29113               0         58            53            51            0.0   
29114               0         61            70            67            1.0   
29115               0         82            90            93            1.0   
29116               0         64            60            58            0.0   

       Gender_male  LunchType_free/reduced  LunchType_standard  Grade  \
0              0.0                     0.0                 1.0      1   
1              0.0                     0.0                 1.0      1   
2              0.0                     0.0                 1.0      1   
3              1.0                     1.0                 0.0      0   
4              1.0                     0.0                 1.0      1   
...            ...                     ...                 ...    ...   
29112          0.0                     0.0                 1.0      1   
29113          1.0                     0.0                 1.0      1   
29114          0.0                     1.0                 0.0      1   
29115          0.0                     0.0                 1.0      1   
29116          1.0                     0.0                 1.0      1   

      gender_numeric  
0                  1  
1                  1  
2                  1  
3                  0  
4                  0  
...              ...  
29112              1  
29113              0  
29114              1  
29115              1  
29116              0  

[29117 rows x 21 columns]

In [55]:
X = df[feature_cols]
y = df.Grade
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

rf_model = RandomForestClassifier(max_depth=5, n_estimators=20, random_state=42)
rf_model.fit(X,y)

# Predict on the testing set
y_pred = rf_model.predict(X_test)

# Display confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

# Display precision, recall, and F1 score for all grades
class_report = classification_report(y_test, y_pred)
print("\nClassification Report:")
print(class_report)

[[   0 1174]
 [   0 7562]]

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00      1174
           1       0.87      1.00      0.93      7562

    accuracy                           0.87      8736
   macro avg       0.43      0.50      0.46      8736
weighted avg       0.75      0.87      0.80      8736



c:\Users\Korisnik\AppData\Local\Programs\Python\Python39-32\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Korisnik\AppData\Local\Programs\Python\Python39-32\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Korisnik\AppData\Local\Programs\Python\Python39-32\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _wa

6. Compare the results. Did our model work better in the first case or the second? Explain why and suggest a way to improve it.

Our model worked much better in second case. In case there are imbalances in the distribution of grades from 1 to 5, the model can struggle to
accurately predict the minority classes. Binary classification often helps address class imbalance issues,
as it focuses on distinguishing between two broadly defined categories, so it is why the second model works better. Predicting specific grades involves distinguishing among multiple classes, which
can be challenging, especially if the data is noisy or if there are subtle differences between adjacent
grades. By simplifying the problem to binary classification (pass or fail), the model has a less complex
task, making it easier to learn and generalize.

We could further improve model with cross validation. This would help our model to ensure that the model's performance is not overly dependent on the specific split of training and testing data. We could also consider creating or selecting more relevant features that capture essential information about student's academic performance. Feature engineering can significantly impact the
model's performance.